#!/bin/bash

for value in {1..10}
do
    echo OUTPUT FOR TEST CASE $value
    echo ---------------------------  
    source ./p2 testfiles/test$value
    echo --------------------------- 
    echo
    if [ "$value" = 10 ]; then
        echo 'Press RETURN to exit.'
    else 
        echo 'Press RETURN for next test.'
    fi
    read -r b
done
